name: QR Backend CI/CD and Upload QR Codes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load .env file
        run: |
          echo "Loading .env file..."
          set -a
          source .env
          set +a

      - name: Print debug information (Check environment variables)
        run: |
          echo "REPO_OWNER is: $REPO_OWNER"
          echo "REPO_NAME is: $REPO_NAME"
          echo "MY_GITHUB_TOKEN is: $MY_GITHUB_TOKEN"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest test_main.py --maxfail=1 --disable-warnings -q

      - name: Run the application
        run: |
          uvicorn main:app --reload & sleep 10

      - name: Check generated QR codes
        run: |
          ls -l qr_codes/

  upload-qr-code:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load .env file
        run: |
          echo "Loading .env file..."
          set -a
          source .env
          set +a

      - name: Print debug information (Check environment variables)
        run: |
          echo "REPO_OWNER is: $REPO_OWNER"
          echo "REPO_NAME is: $REPO_NAME"
          echo "MY_GITHUB_TOKEN is: $MY_GITHUB_TOKEN"

      - name: Upload QR codes to GitHub
        run: |
          echo "Deploying QR codes..."
          for qr_code in qr_codes/*.png; do
            file_name=$(basename "$qr_code")
            base64_image=$(base64 "$qr_code" | tr -d '\n')
            curl -X PUT \
              -H "Authorization: token $MY_GITHUB_TOKEN" \
              -d "{\"message\":\"Add QR code for $file_name\",\"content\":\"$base64_image\",\"branch\":\"main\"}" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/qr_codes/$file_name"
          done

      - name: Verify upload status
        run: |
          echo "QR Codes uploaded successfully."
