name: QR Backend CI/CD and Upload QR Codes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Installer pytest pour exécuter les tests

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          pytest main_test.py --maxfail=1 --disable-warnings -q  # Spécifiez le fichier de test

      # Étape 5 : Construire l'application (si les tests passent)
      - name: Run the application
        run: |
          uvicorn main:app --reload & sleep 10  # Lancer temporairement pour valider

      # Étape 6 : Vérifier les QR Codes générés
      - name: Check generated QR codes
        run: |
          ls -l qr_codes/

  upload-qr-code:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Télécharger les QR codes sur GitHub
      - name: Upload QR codes to GitHub
        run: |
          echo "Deploying QR codes..."
          # Exemple : Télécharger les images des QR codes sur GitHub.
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: QR-Backend
          BRANCH_NAME: main
