name: QR Backend CI/CD and Upload QR Codes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write # Permet l'accès en écriture au dépôt

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Étape 4 : Ajouter le token GitHub comme variable d'environnement
      - name: Set up GitHub token
        run: echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Étape 5 : Exécuter les tests
      - name: Run tests
        run: |
          pytest test_main.py --maxfail=1 --disable-warnings -q

      # Étape 6 : Construire et valider l'application
      - name: Validate application
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 & sleep 10
          pkill -f uvicorn

  upload-qr-code:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Télécharger les QR codes sur GitHub
      - name: Upload QR codes to GitHub
        run: |
          echo "Deploying QR codes..."
          for file in qr_codes/*.png; do
            echo "Uploading $file to GitHub..."
            base64_content=$(base64 "$file" | tr -d '\n')
            filename=$(basename "$file")
            curl -X PUT \
              -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d '{
                "message": "Add QR code: '"$filename"'",
                "content": "'"$base64_content"'"
              }' \
              https://api.github.com/repos/${{ github.repository_owner }}/QR-Backend/contents/qr_codes/"$filename"
          done
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
