name: QR Backend CI/CD and Upload QR Codes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest test_main.py --maxfail=1 --disable-warnings -q

      - name: Run the application
        run: |
          uvicorn main:app --reload & sleep 10

      - name: Check generated QR codes
        run: |
          ls -l qr_codes/

  upload-qr-code:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload QR codes to GitHub
        run: |
          echo "Deploying QR codes..."
          for qr_code in qr_codes/*.png; do
            file_name=$(basename "$qr_code")
            base64_image=$(base64 "$qr_code" | tr -d '\n')
            curl -X PUT \
              -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
              -d "{\"message\":\"Add QR code for $file_name\",\"content\":\"$base64_image\",\"branch\":\"main\"}" \
              "https://api.github.com/repos/mounamahfd/QR-Backend/contents/qr_codes/$file_name"
          done

      - name: Verify upload status
        run: |
          echo "QR Codes uploaded successfully."
